(setq user-mail-address "sidhartharya10@gmail.com")
(setq user-full-name "Sidharth Arya")
;; (setq smtpmail-smtp-server "smtp.gmail.com")
;; (setq smtpmail-smtp-service 587)
(setq shr-use-colors nil)
(setq shr-use-fonts nil)
