(defun org-agenda()
     (interactive)
     (start-process-shell-command "*Agenda*" nil "sh ~/.config/sxhkd/scripts/activate.sh wname Org'")
     (start-process-shell-command "*Agenda*" nil "emacsclient --eval '(org-agenda)'")
     )
(global-set-key (kbd "C-c a") #'org-agenda)
